config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "static_pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  #basic login
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :services
  resources :categories
  resources :locations
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :category
    belongs_to :location

    def available_days_display
        available_days.map { |day| Date::DAYNAMES[day] }.join(", ")
      end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        @locations = Location.all.order(:created_at)
        
        # if session[:user_id]
        #     @user = User.find(session[:user_id])
        # end
    end

    def new
        @location = Location.new
    end

    def create
        @location = Location.new(location_params)
        if @location.save 
            redirect_to locations_path, notice: 'Location has been created successfully.'
        else
            render :new, status: 422
        end
    end

def show 
end

def edit 
    if @location.user != Current.user
        redirect_to locations_path, notice: 'unauthorized access!'
     end
end

def update
    if @location.update(location_params)
        redirect_to locations_path, notice: 'Location has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    if @location.user != Current.user
        redirect_to locations_path, notice: 'unauthorized access!'
    else @location.destroy
    redirect_to locations_path, notice: 'Location has been deleted successfully.'
    end
end


private

    def location_params
        params.require(:location).permit(:name, :admin_id)
    end

    def set_location
        @location = Location.find(params[:id])
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :set_service, only: %i[show edit update destroy]
    def index
        @services = Service.all.order(:created_at)
        
        # if session[:user_id]
        #     @user = User.find(session[:user_id])
        # end
    end

    def new
        @service = Service.new
    end

    def create
        @service = Service.new(service_params)
        if @service.save 
            redirect_to services_path, notice: 'Service has been created successfully.'
        else
            render :new, status: 422
        end
    end

def show 
end

def edit 
    if @service.user != Current.user
        redirect_to services_path, notice: 'unauthorized access!'
     end
end

def update
    if @service.update(service_params)
        redirect_to services_path, notice: 'Service has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    if @service.user != Current.user
        redirect_to services_path, notice: 'unauthorized access!'
    else @service.destroy
    redirect_to services_path, notice: 'Service has been deleted successfully.'
    end
end


private

    def service_params
        params.require(:service).permit(:name, :description, :price, available_days: [], :available_time_start, :available_time_end, :category_id, :location_id)
    end

    def set_service
        @service = Service.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end



    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        
        else
            flash[:alert] = "Invalid email or password"
            render :new, status: 422
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Booking Looking</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= render partial: "shared/navbar"%>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
</br>

<div class="container">
<% if flash[:notice]%>
<div class ="alert alert-info mt-4">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert]%>
<div class ="alert alert-warning mt-4">
    <%= flash[:alert] %>
</div>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#", style="margin-left: 60px;">Booking Looking.</a>
<div style="margin-right: 30px;">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto", style="margin-right: 60px;">
      <li class="nav-item active" style="margin-left: 30px;">
      <% if Current.user %>
      <%= link_to 'Home','#', class: 'nav-link' %>
<% end %>
      <% if !Current.user %>
      <li class="nav-item" style="margin-left: 30px;">
        <a class="nav-link" href="sign_in">Sign In</a>
      </li>
      <% end %>
      <% if Current.user %>
      <li class="dropdown" style="margin-left: 30px;">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%=Current.user.first_name%>
      </a>
      
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
 
        <li><a class="dropdown-item" href="#">My Products</a></li>
      
        <li><a class="dropdown-item" href="#">My Biddings</a></li>
      
        <li><%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </li>
    <% end %>
</nav>

