config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "static_pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  #basic login
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :services
  resources :categories
  resources :locations
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :category
    belongs_to :location

    def available_days_display
        available_days.map { |day| Date::DAYNAMES[day] }.join(", ")
      end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    
    def set_current_user 
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all.order(:created_at)
        
        # if session[:user_id]
        #     @user = User.find(session[:user_id])
        # end
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save 
            redirect_to categories_path, notice: 'Category has been created successfully.'
        else
            render :new, status: 422
        end
    end

def show 
end

def edit 
    if @category.user != Current.user
        redirect_to services_path, notice: 'unauthorized access!'
     end
end

def update
    if @category.update(category_params)
        redirect_to categories_path, notice: 'Category has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    if @category.user != Current.user
        redirect_to categories_path, notice: 'unauthorized access!'
    else @category.destroy
    redirect_to categories_path, notice: 'Category has been deleted successfully.'
    end
end


private

    def category_params
        params.require(:category).permit(:name, :description, :admin_id)
    end

    def set_category
        @category = Category.find(params[:id])
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        @locations = Location.all.order(:created_at)
        
        # if session[:user_id]
        #     @user = User.find(session[:user_id])
        # end
    end

    def new
        @location = Location.new
    end

    def create
        @location = Location.new(location_params)
        if @location.save 
            redirect_to locations_path, notice: 'Location has been created successfully.'
        else
            render :new, status: 422
        end
    end

def show 
end

def edit 
    if @location.user != Current.user
        redirect_to locations_path, notice: 'unauthorized access!'
     end
end

def update
    if @location.update(location_params)
        redirect_to locations_path, notice: 'Location has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    if @location.user != Current.user
        redirect_to locations_path, notice: 'unauthorized access!'
    else @location.destroy
    redirect_to locations_path, notice: 'Location has been deleted successfully.'
    end
end


private

    def location_params
        params.require(:location).permit(:name, :admin_id)
    end

    def set_location
        @location = Location.find(params[:id])
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :set_service, only: %i[show edit update destroy]
    def index
        @services = Service.all.order(:created_at)
        
        # if session[:user_id]
        #     @user = User.find(session[:user_id])
        # end
    end

    def new
        @service = Service.new
    end

    def create
        @service = Service.new(service_params)
        if @service.save 
            redirect_to services_path, notice: 'Service has been created successfully.'
        else
            render :new, status: 422
        end
    end

def show 
end

def edit 
    if @service.user != Current.user
        redirect_to services_path, notice: 'unauthorized access!'
     end
end

def update
    if @service.update(service_params)
        redirect_to services_path, notice: 'Service has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    if @service.user != Current.user
        redirect_to services_path, notice: 'unauthorized access!'
    else @service.destroy
    redirect_to services_path, notice: 'Service has been deleted successfully.'
    end
end


private

    def service_params
        params.require(:service).permit(:name, :description, :price, available_days: [], :available_time_start, :available_time_end, :category_id, :location_id)
    end

    def set_service
        @service = Service.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end



    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        
        else
            flash[:alert] = "Invalid email or password"
            render :new, status: 422
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.description %></td>
          <td><%= link_to "Show", category %></td>
          <td><%= link_to "Edit", edit_category_path(category) %></td>
          <td><%= link_to "Delete", category, method: :delete, data: { confirm: "Are you sure you want to delete this category?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New Category", new_category_path, class: "btn btn-primary" %>
</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= form_with(model: @category, url: categories_path) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Category", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/locations/index.html.erb
<div class="container">
  <h1>Locations</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td><%= location.name %></td>
          <td><%= link_to "Show", location %></td>
          <td><%= link_to "Edit", edit_location_path(location) %></td>
          <td><%= link_to "Delete", location, method: :delete, data: { confirm: "Are you sure you want to delete this location?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New Location", new_location_path, class: "btn btn-primary" %>
</div>

app/views/locations/new.html.erb
<div class="container">
<h1>New Location</h1>

<%= form_with(model: @location, url: locations_path) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Category", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/services/index.html.erb
<div class="container">
  <h1>Services</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Category</th>
        <th>Location</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.name %></td>
          <td><%= service.description %></td>
          <td><%= service.category.name %></td>
          <td><%= service.location.name %></td>
          <td><%= link_to "Show", service %></td>
          <td><%= link_to "Edit", edit_service_path(service) %></td>
          <td><%= link_to "Delete", service, method: :delete, data: { confirm: "Are you sure you want to delete this service?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New Service", new_service_path, class: "btn btn-primary" %>
</div>

app/views/services/new.html.erb
<div class="container">
<h1>New Service</h1>

<%= form_with(model: @service, url: services_path) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>

  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>

  <%= form.label :price %>
  <%= form.number_field :price, class: "form-control" %>

  <%= form.label :available_date %>
  <%= form.date_field :available_date, class: "form-control" %>

  <%= form.label :available_time %>
  <%= form.time_field :available_time, class: "form-control" %>

  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true, class: "form-control" %>

  <%= form.label :location_id %>
  <%= form.collection_select :location_id, Location.all, :id, :name, prompt: true, class: "form-control" %>

  <%= form.submit "Create Service", class: "btn btn-primary" %>
<% end %>
</div>